apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
  - port: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-page
data:
  index.html: |
    <html>
      <body>
        Nothing to see here.
      </body>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: index-page
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 50m
      volumes:
      - name: index-page
        configMap:
          name: hello-page

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello
  targetCPUUtilizationPercentage: 20
status:
  currentReplicas: 0
  desiredReplicas: 0
